const theme = (theme) => ({
  input: {
    backgroundColor: "#efeff4",
    border: "1px solid #ddd",
    borderRadius: "30px",
    width: "95%",
    height: "40px",
    outline: "none",
    padding: "5px",
    fontFamily: "Vazirmatn",
    marginBottom: "20px",
  },
  button: {
    backgroundColor: "#fc0",
    border: 0,
    borderRadius: "25px",
    padding: "10px",
    width: "95%",
    height: "40px",
    marginTop: "5px",
    fontFamily: "Vazirmatn",
    fontWeight: 700,
    fontSize: "16px",
  },
  title: {
    fontSize: "18px",
    fontWeight: 700,
    display: "flex",
    justifyContent: "center",
    marginBottom: "35px",
  },
  simType: {
    display: "flex",
    justifyContent: "center",
    color: "#8b8b8d",
    fontWeight: 400,
    marginBottom: "10px",
    fontSize: "14px",
  },
  wow: {
    display: "flex",
    alignItems: "center",
    marginRight: "35px",
    marginBottom: "0.5rem",
  },
  price: {
    color: "#8b8b8d",
    fontSize: "14px",
    fontWeight: 400,
    marginBottom: "15px",
  },
  section_container: {
    direction: "rtl",
    display: "flex",
    // alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    padding: "40px",
    marginTop: "40px",
    borderRadius: "10px",
    width: "100%",
  },
  minMax: {
    display: "flex",
    justifyContent: "center",
    color: "#8b8b8d",
    fontSize: "12px",
    marginTop: "-10px",
    marginBottom: "10px",
  },
});

export default theme;
